old_sound_rabbit_mq:
  connections:
    default:
      host: '%env(RABBITMQ_HOST)%'
      user: '%env(RABBITMQ_USER)%'
      password: '%env(RABBITMQ_PASSWORD)%'
      vhost: '%env(RABBITMQ_VHOST)%'
  producers:
    sms:
      connection: default
      class: App\Producer\SmsProducer
      exchange_options:
        name: sms
        type: direct
  consumers:
    sms:
      connection:       default
      exchange_options: {name: 'sms', type: direct}
      queue_options:    {name: 'sms'}
      callback:         sms_service
