index:
  path: /
  methods: [GET, POST]
  controller: App\Controller\HomeController::index

messages:
  path: /messages
  methods: GET
  controller: App\Controller\MessagesController::index

messages_data:
  path: /messages/list
  methods: GET
  controller: App\Controller\MessagesController::show

messages_webhook:
  path: /messages/webhook/{id}
  methods: POST
  controller: App\Controller\MessagesController::webhook